export { default as Carousel } from './Carousel'
export { default as HeroLema } from './HeroLema'
export { default as Testimonials } from './Testimonials'
export { default as CTASection } from './CTASection'
export { default as Home } from './Home'
